"use client"

import { useState } from 'react'
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"
import { Upload, Sparkles, FileText, Download } from "lucide-react"
import { Badge } from "@/components/ui/badge"

export default function ClientBriefPage() {
  const [isGenerating, setIsGenerating] = useState(false)
  const [briefGenerated, setBriefGenerated] = useState(false)

  const handleGenerate = () => {
    setIsGenerating(true)
    setTimeout(() => {
      setIsGenerating(false)
      setBriefGenerated(true)
    }, 2000)
  }

  return (
    <div className="flex flex-col space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">AI Client Brief Generator</h2>
          <p className="text-muted-foreground text-sm mt-1">Transform meeting notes and transcripts into structured architectural briefs.</p>
        </div>
        {briefGenerated && (
          <Button variant="outline">
            <Download className="mr-2 h-4 w-4" />
            Export PDF
          </Button>
        )}
      </div>

      {!briefGenerated ? (
        <div className="grid gap-6 md:grid-cols-2">
          <Card className="border-border bg-card">
            <CardHeader>
              <CardTitle>Input Data</CardTitle>
              <CardDescription>Paste raw notes or upload a meeting transcript.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="border-2 border-dashed border-border rounded-lg p-6 flex flex-col items-center justify-center text-center cursor-pointer hover:bg-muted/50 transition-colors">
                <Upload className="h-8 w-8 text-muted-foreground mb-4" />
                <p className="text-sm font-medium text-foreground">Click to upload transcript</p>
                <p className="text-xs text-muted-foreground mt-1">Supports PDF, DOCX, TXT</p>
              </div>
              <div className="relative">
                <div className="absolute inset-0 flex items-center">
                  <span className="w-full border-t border-border" />
                </div>
                <div className="relative flex justify-center text-xs uppercase">
                  <span className="bg-card px-2 text-muted-foreground">Or paste text</span>
                </div>
              </div>
              <Textarea placeholder="Paste raw meeting notes, client emails, or ideas here..." className="min-h-[200px] resize-none" />
              <Button className="w-full" onClick={handleGenerate} disabled={isGenerating}>
                {isGenerating ? "Analyzing..." : (
                  <>
                    <Sparkles className="mr-2 h-4 w-4" />
                    Generate Architecture Brief
                  </>
                )}
              </Button>
            </CardContent>
          </Card>
          
          <div className="hidden md:flex flex-col items-center justify-center border border-border bg-muted/30 rounded-xl text-center p-8">
             <FileText className="h-16 w-16 text-muted-foreground/50 mb-4" />
             <h3 className="text-lg font-medium text-foreground">Ready to Generate</h3>
             <p className="text-sm text-muted-foreground mt-2 max-w-sm">
               Archnova AI will extract goals, spatial requirements, budget expectations, and site constraints from your raw input.
             </p>
          </div>
        </div>
      ) : (
        <Card className="border-border bg-card">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Client Brief: Lake House Renovation</CardTitle>
              <Badge variant="secondary">Generated by AI</Badge>
            </div>
            <CardDescription>Extracted on Oct 24, 2026</CardDescription>
          </CardHeader>
          <CardContent className="space-y-8">
            <div className="space-y-2">
              <h3 className="text-lg font-semibold text-foreground border-b border-border pb-2">Executive Summary</h3>
              <p className="text-sm text-muted-foreground leading-relaxed pt-2">
                The client, Sarah Jenkins, seeks to comprehensively renovate a 4,500 sqft lakefront property in Austin, TX. The primary goal is to modernize the aesthetic while heavily emphasizing "indoor-outdoor flow". The client wishes to maximize natural light and views of the lake while ensuring the home remains practical for entertaining large groups.
              </p>
            </div>
            
            <div className="space-y-2">
              <h3 className="text-lg font-semibold text-foreground border-b border-border pb-2">Spatial Requirements</h3>
              <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 pt-2">
                <li>Primary suite with lake views and expanded walk-in closet</li>
                <li>Open-concept kitchen/living area with operable glass walls (e.g., NanaWall)</li>
                <li>3 secondary bedrooms with en-suite baths</li>
                <li>Dedicated home office with acoustic privacy</li>
                <li>Expanded outdoor decking with integrated kitchen and fire pit</li>
              </ul>
            </div>

            <div className="grid md:grid-cols-2 gap-8">
              <div className="space-y-2">
                <h3 className="text-lg font-semibold text-foreground border-b border-border pb-2">Budget & Timeline</h3>
                <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 pt-2">
                  <li><strong className="text-foreground">Target Budget:</strong> $1.5M - $1.8M (Hard cap at $2M)</li>
                  <li><strong className="text-foreground">Target Completion:</strong> Summer 2027</li>
                  <li><strong className="text-foreground">Phasing:</strong> Prefer single-phase construction</li>
                </ul>
              </div>
              <div className="space-y-2">
                <h3 className="text-lg font-semibold text-foreground border-b border-border pb-2">Key Constraints & Risks</h3>
                <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 pt-2">
                  <li>Local conservation zoning restricts expansion footprint</li>
                  <li>Client expressed concern regarding material cost volatility</li>
                  <li>Site access is constrained due to the narrow driveway</li>
                </ul>
              </div>
            </div>

            <div className="flex justify-end pt-4 space-x-4">
              <Button variant="outline" onClick={() => setBriefGenerated(false)}>Edit Inputs</Button>
              <Button>Save to Project Documents</Button>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
